# Generated by Django 4.2.6 on 2023-10-12 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
            options={
                'verbose_name': 'advertisement',
                'verbose_name_plural': 'advertisements',
            },
        ),
        migrations.CreateModel(
            name='cmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField()),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'cmp',
                'verbose_name_plural': 'cmps',
            },
        ),
        migrations.CreateModel(
            name='companie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
            options={
                'verbose_name': 'companie',
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
            options={
                'verbose_name': 'permission',
                'verbose_name_plural': 'permissions',
            },
        ),
        migrations.CreateModel(
            name='jobapplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.advertisement')),
                ('id_cmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.cmp')),
            ],
            options={
                'verbose_name': 'jobapplication',
                'verbose_name_plural': 'jobapplications',
            },
        ),
        migrations.AddField(
            model_name='cmp',
            name='id_permissions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utilisateur.permissions'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='id_companies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.companie'),
        ),
    ]
