# Generated by Django 4.2.6 on 2023-10-13 14:46

from django.db import migrations, models
import django.db.models.deletion
import utilisateur.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'companies',
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
            options={
                'verbose_name': 'permission',
                'verbose_name_plural': 'permissions',
            },
        ),
        migrations.CreateModel(
            name='cmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('companies', models.ForeignKey(default=utilisateur.models.get_first_company, on_delete=django.db.models.deletion.CASCADE, to='utilisateur.companies')),
                ('permissions', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utilisateur.permissions')),
            ],
            options={
                'verbose_name': 'cmp',
                'verbose_name_plural': 'cmps',
            },
        ),
        migrations.CreateModel(
            name='advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.CharField()),
                ('companies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.companies')),
            ],
            options={
                'verbose_name': 'advertisement',
                'verbose_name_plural': 'advertisements',
            },
        ),
    ]
