# Generated by Django 4.2.6 on 2023-10-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
            options={
                'verbose_name': 'permission',
                'verbose_name_plural': 'permissions',
            },
        ),
        migrations.AlterModelOptions(
            name='cmp',
            options={'verbose_name': 'cmp', 'verbose_name_plural': 'cmps'},
        ),
    ]
