# Generated by Django 4.2.6 on 2023-10-17 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='cmp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utilisateur.cmp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cmp',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
