# Generated by Django 4.2.6 on 2023-10-11 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={'verbose_name': 'permission', 'verbose_name_plural': 'permissions'},
        ),
        migrations.AddField(
            model_name='cmp',
            name='id_permissions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utilisateur.permissions'),
        ),
    ]
