# Generated by Django 4.2.6 on 2023-10-13 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_permissions_alter_cmp_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmp',
            name='permissions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utilisateur.permissions'),
        ),
    ]
