# Generated by Django 4.2.6 on 2023-10-11 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0003_alter_permissions_options_cmp_id_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cmp',
            options={'verbose_name': 'cmp', 'verbose_name_plural': 'cmps'},
        ),
        migrations.CreateModel(
            name='jobapplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.cmp')),
            ],
        ),
    ]
