# Generated by Django 4.2.6 on 2023-10-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0004_alter_cmp_options_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='companie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
            options={
                'verbose_name': 'companie',
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'verbose_name': 'jobapplication', 'verbose_name_plural': 'jobapplications'},
        ),
    ]
