# Generated by Django 4.2.6 on 2023-10-11 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0005_companie_alter_jobapplication_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_companies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.companie')),
            ],
            options={
                'verbose_name': 'advertisement',
                'verbose_name_plural': 'advertisements',
            },
        ),
    ]
