# Generated by Django 4.2.6 on 2023-10-11 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0006_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='id_advertisement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utilisateur.advertisement'),
            preserve_default=False,
        ),
    ]
