# Generated by Django 4.2.6 on 2023-10-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0007_jobapplication_id_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='name',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
