# Generated by Django 4.2.6 on 2023-10-10 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compte', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='compte',
            new_name='cmp',
        ),
    ]
