# Generated by Django 4.2.6 on 2023-10-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superuser', models.CharField()),
                ('companies_name', models.CharField(max_length=50)),
                ('description', models.CharField()),
            ],
        ),
    ]
