# Generated by Django 4.2.6 on 2023-10-17 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superuser', models.CharField()),
                ('companies_name', models.CharField(max_length=50)),
                ('description', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField()),
                ('first_name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.cmp')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.companies')),
            ],
        ),
    ]
